"""add unit to products

Revision ID: 0a8bf3ce0d53
Revises: c05b0ad3d248
Create Date: 2026-01-26 02:10:12.509401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8bf3ce0d53'
down_revision = 'c05b0ad3d248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
