"""add recipe favorites and ratings

Revision ID: 64d845a01c93
Revises: e53c004119a2
Create Date: 2026-06-30 23:12:20.979703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d845a01c93'
down_revision = 'e53c004119a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_id', name='uq_user_recipe_favorite')
    )
    with op.batch_alter_table('recipe_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_favorites_recipe_id'), ['recipe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('recipe_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('stars >= 1 AND stars <= 5', name='ck_rating_stars_range'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_id', name='uq_user_recipe_rating')
    )
    with op.batch_alter_table('recipe_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_ratings_recipe_id'), ['recipe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ratings_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_ratings_user_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_ratings_recipe_id'))

    op.drop_table('recipe_ratings')
    with op.batch_alter_table('recipe_favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_favorites_recipe_id'))

    op.drop_table('recipe_favorites')
    # ### end Alembic commands ###
